// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextConfPro.Services.EventAPI.Data;

#nullable disable

namespace NextConfPro.Services.EventAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240117153041_AddEventToDb")]
    partial class AddEventToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NextConfPro.Services.EventAPI.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Location = "Test Location 1",
                            Name = "The Best Conference Ever",
                            StartTime = new DateTime(2024, 1, 17, 10, 30, 41, 239, DateTimeKind.Local).AddTicks(5250)
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Location = "Test Location 2",
                            Name = "The Second Best Conference Ever",
                            StartTime = new DateTime(2024, 1, 17, 10, 30, 41, 239, DateTimeKind.Local).AddTicks(5290)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
